language: generic

sudo: false

notifications:
  email: false

matrix:
  fast_finish: true
  include:
    - os: linux
      language: python
      python: 3.4
      env:
        - CC=gcc-4.9
        - CXX=g++-4.9
    - os: linux
      language: python
      python: 3.5
      env:
        - CC=gcc-4.9
        - CXX=g++-4.9
    - os: linux
      language: python
      python: 3.6
      env:
        - CC=gcc-4.9
        - CXX=g++-4.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

install:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
  - python -m pip install -r tests/requirements.txt
  - python setup.py build_ext --inplace
  - python -m pip install -e .

script:
  - python -m moderngl
  - python -m pytest tests/test_local.py tests/test_module_integrity.py tests/test_code_style.py tests/test_documentation.py
